# Generated by Django 6.0.6 on 2026-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
